<div class="field bizreward number required">
    <label class="label" for="bizrewardnumber">
      <span><?= $block->escapeHtml(__('Bizreward Number')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="bizrewardnumber" id="bizrewardnumber" value="" title="<?= $block->escapeHtmlAttr(__('Bizreward Number')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>